<?php
    /**
     * Created by PhpStorm.
     * User: Administrator
     * Date: 2018/9/26
     * Time: 11:38
     */

namespace app\manager\controller;

use app\manager\validate\AdminMustValidate;
use think\Request;
use app\manager\model\Admin as adminModel;

class Admin extends Base
{
    protected $admin = null;
    public function _initialize()
    {
        $this->admin = new adminModel();
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**管理员列表*/
    public function adminList(Request $request)
    {
        $data = $request->param();
        $list = $this->admin->listMess(12, $data);
        // 把分页数据赋值给模板变量list
        $this->assign('list', $list);
        return $this->fetch('adminList', ['top_name'=>'管理员列表', 'version'=>'1.0', 'search'=>$data?$data:['search'=>'']]);
    }

    /**管理员列表*/
    public function adminTrash(Request $request)
    {
        $data = $request->param();
        $list = $this->admin->listMess(12, $data, 9);
        // 把分页数据赋值给模板变量list
        $this->assign('list', $list);
        return $this->fetch('adminList', ['top_name'=>'管理员回收站列表', 'version'=>'1.0', 'search'=>$data?
            $data:['search'=>'']]);
    }


    /**管理员的curd操作*/
    public function curdAdmin(Request $request)
    {
        if ($request->isPost()) {
            $data = $request->param();
            $_SESSION['think']['__token__'] = $data['__token__'];
            $errorData = (new AdminMustValidate())->goCheck();
            if ($errorData !== true) {
                return redirect('/manager/curdAdmin', [], 500, ['error'=>$errorData,'data' => $data]);
            }
            /**处理数据*/
            $ret = $this->admin->curdAdminMessage($request);
            if ($ret) {
                $this->success(isset($data['id'])&&$data['id']>0?'修改成功':'添加成功', '/manager/adminList', [], 1);
            } else {
                return redirect('/manager/curdAdmin', [], 500, ['error'=>[isset($data['id'])&&$data['id']
                    ?'修改失败':'添加失败'],'data' => $data]);
            }
        } else {
            $data = $request->param();
            if ($data) {
                $ret = $this->admin->editOneAdmin($data['id']);
            } else {
                $ret['id'] = 0;
                $ret['name'] = '';
                $ret['account'] = '';
                $ret['password'] = 'zanpu';
                $ret['pic'] = '';
            }
            return $this->fetch('curdAdmin', ['top_name'=>'管理员列表', 'version'=>'1.0', 'ret'=>$ret]);
        }
    }

    /**删除操作*/
    public function restoreDelAdmin(Request $request)
    {
        $data = $request->param();
        $status = $data['status'];
        if ($this->admin->delAdmin($data['id'], $status)) {
            $this->success($status?'删除成功':'还原成功', '/manager/adminList', [], 1);
        } else {
            $this->error($status?'删除失败':'还原', [], [], 1);
        }
    }
}
