<?php
    /**
     * Created by PhpStorm.
     * User: Administrator
     * Date: 2018/9/27
     * Time: 11:29
     */

namespace app\manager\controller;

use app\manager\model\Config as configModel;
use think\Request;

class Config extends Base
{
    protected $linkModel = null;
    public function _initialize()
    {
        $this->linkModel = new configModel();
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function curdConfig(Request $request)
    {
        if ($request->isPost()) {
            $data = $request->param();
            $_SESSION['think']['__token__'] = $data['__token__'];
            /**处理数据*/
            $ret = $this->linkModel->curdMess($request);
            if ($ret) {
                $this->success(isset($data['id'])&&$data['id']>0?'修改成功':'添加成功', '/config/curdConfig', [], 1);
            } else {
                return redirect('/config/curdConfig', [], 500, ['error'=>[isset($data['id'])&&$data['id']
                    ?'修改失败':'添加失败'],'data' => $data]);
            }
        } else {
            $ret = $this->linkModel->editOneConfig(1);
            return $this->fetch('curdConfig', ['top_name'=>'网站配置', 'version'=>'1.0', 'ret'=>$ret]);
        }
    }
}
