<?php
    /**
     * Created by PhpStorm.
     * User: Administrator
     * Date: 2018/9/27
     * Time: 11:29
     */

namespace app\manager\controller;

use app\manager\model\Jobs as JobsModel;
use app\manager\validate\JobsMustValidate;
use think\Request;

class Jobs extends Base
{
    protected $linkModel = null;
    public function _initialize()
    {
        $this->linkModel = new JobsModel();
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function jobsList(Request $request)
    {
        $data = $request->param();
        $list = $this->linkModel->jobsList(2, $data);
        $this->assign('list', $list);
        return $this->fetch('jobsList', ['top_name'=>'招聘', 'version'=>'1.0', 'search'=>
            $data?$data:['search'=>'']]);
    }

    public function curdJobs(Request $request)
    {
        if ($request->isPost()) {
            $data = $request->param();
            $_SESSION['think']['__token__'] = $data['__token__'];
            $errorData = (new JobsMustValidate())->goCheck();
            if ($errorData !== true) {
                return redirect('/jobs/curdJobs', [], 500, ['error'=>$errorData,'data' => $data]);
            }
            /**处理数据*/
            $ret = $this->linkModel->curdMess($request);
            if ($ret) {
                $this->success(isset($data['id'])&&$data['id']>0?'修改成功':'添加成功', '/jobs/jobsList', [], 1);
            } else {
                return redirect('/jobs/curdJobs', [], 500, ['error'=>[isset($data['id'])&&$data['id']
                    ?'修改失败':'添加失败'],'data' => $data]);
            }
        } else {
            $data = $request->param();
            if ($data) {
                $ret = $this->linkModel->editOneJobs($data['id']);
            } else {
                $ret['id'] = 0;
                $ret['num'] = '';
                $ret['title'] = '';
                $ret['jobs_num'] = '';
                $ret['jobs_status'] = '';
                $ret['company_size'] = '';
                $ret['company_nature'] = '';
                $ret['company_tmt'] = '';
                $ret['edu'] = '';
                $ret['salary'] = '';
                $ret['job_nature'] = '';
                $ret['work_exp'] = '';
                $ret['man_exp'] = '';
                $ret['job_desc'] = '';
                $ret['job_require'] = '';
            }
            return $this->fetch('curdJobs', ['top_name'=>'岗位列表', 'version'=>'1.0', 'ret'=>$ret]);
        }
    }


    public function jobsTrash(Request $request)
    {
        $data = $request->param();
        $list = $this->linkModel->jobsList(12, $data, 9);
        $this->assign('list', $list);
        return $this->fetch('jobsList', ['top_name'=>'岗位回收站', 'version'=>'1.0', 'search'=>
            $data?$data:['search'=>'']]);
    }

    public function restoreDelJobs(Request $request)
    {
        $data = $request->param();
        $status = $data['status'];
        $id = $data['id'];
        $ret = $this->linkModel->delJobs($id, $status);
        if ($ret) {
            $this->success($status?'删除成功':'还原成功', '/jobs/jobsList', [], 1);
        } else {
            $this->error($status?'删除失败':'还原失败', '/jobs/jobsList', [], 1);
        }
    }
}
