<?php
    /**
     * Created by PhpStorm.
     * User: Administrator
     * Date: 2018/9/27
     * Time: 11:29
     */

namespace app\manager\controller;

use think\Request;
use app\manager\model\Message as messageModel;

class Message extends Base
{
    protected $linkModel = null;
    public function _initialize()
    {
        $this->linkModel = new messageModel();
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function messageList(Request $request)
    {
        $data = $request->param();
        $list = $this->linkModel->messageList(2, $data);
        $this->assign('list', $list);
        return $this->fetch('messageList', ['top_name'=>'留言管理', 'version'=>'1.0', 'search'=>
            $data?$data:['search'=>'']]);
    }

    public function restoreDelMessage(Request $request)
    {
        $data = $request->param();
        $status = $data['status'];
        $id = $data['id'];
        $ret = $this->linkModel->delMessage($id, $status);
        if ($ret) {
            $this->success($status?'删除成功':'还原成功', '/message/messageList', [], 1);
        } else {
            $this->error($status?'删除失败':'还原失败', '/message/messageList', [], 1);
        }
    }
}
