<?php
    /**
     * Created by PhpStorm.
     * User: Administrator
     * Date: 2018/9/27
     * Time: 11:29
     */

namespace app\manager\controller;

use app\manager\model\Navigate;
use app\manager\validate\NavMustValidate;
use think\Request;

class Nav extends Base
{
    protected $navModel = null;
    public function _initialize()
    {
        $this->navModel = new Navigate();
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function navList(Request $request)
    {
        $data = $request->param();
        $list = $this->navModel->navList(20, $data);
        $this->assign('list', $list);
        return $this->fetch('navList', ['top_name'=>'导航列表', 'version'=>'1.0', 'search'=>
            $data?$data:['search'=>'']]);
    }

    public function curdNav(Request $request)
    {
        if ($request->isPost()) {
            $data = $request->param();
            $_SESSION['think']['__token__'] = $data['__token__'];
            $errorData = (new NavMustValidate())->goCheck();
            if ($errorData !== true) {
                return redirect('/nav/curdNav', [], 500, ['error'=>$errorData,'data' => $data]);
            }
            /**处理数据*/
            $ret = $this->navModel->curdMess($request);
            if ($ret) {
                $this->success(isset($data['id'])&&$data['id']>0?'修改成功':'添加成功', '/nav/navList', [], 1);
            } else {
                return redirect('/nav/curdNav', [], 500, ['error'=>[isset($data['id'])&&$data['id']
                    ?'修改失败':'添加失败'],'data' => $data]);
            }
        } else {
            $data = $request->param();
            if ($data) {
                $ret = $this->navModel->editOneNav($data['id']);
            } else {
                $ret['id'] = 0;
                $ret['name'] = '';
                $ret['link'] = '';
                $ret['p_id'] = '';
                $ret['sort'] = '';
            }
            $ret['menu_list'] = $this->navModel->navList(50, $data);
            return $this->fetch('curdNav', ['top_name'=>'导航列表', 'version'=>'1.0', 'ret'=>$ret]);
        }
    }


    public function navTrash(Request $request)
    {
        $data = $request->param();
        $list = $this->navModel->navListTrash(12, $data, 9);
        $this->assign('list', $list);
        return $this->fetch('navList', ['top_name'=>'导航回收站', 'version'=>'1.0', 'search'=>
            $data?$data:['search'=>'']]);
    }

    public function restoreDelNav(Request $request)
    {
        $data = $request->param();
        $status = $data['status'];
        $id = $data['id'];
        $ret = $this->navModel->editFieldNav($id, 'status', $status);
        if ($ret) {
            $this->success($status?'删除成功':'还原成功', '/nav/navList', [], 1);
        } else {
            $this->error($status?'删除失败':'还原失败', '/nav/linkNav', [], 1);
        }
    }
}
