<?php
    /**
     * Created by PhpStorm.
     * User: Administrator
     * Date: 2018/9/27
     * Time: 11:29
     */

namespace app\manager\controller;

use app\manager\model\Pic as picModel;
use app\manager\validate\PicMustValidate;
use think\Request;

class Pic extends Base
{
    protected $model = null;
    public function _initialize()
    {
        $this->model = new picModel();
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function picList(Request $request)
    {
        $data = $request->param();
        $list = $this->model->picList(2, $data);
        $this->assign('list', $list);
        return $this->fetch('picList', ['top_name'=>'图片管理', 'version'=>'1.0', 'search'=>
            $data?$data:['search'=>'']]);
    }

    public function curdPic(Request $request)
    {
        if ($request->isPost()) {
            $data = $request->param();
            //halt($data);
            $_SESSION['think']['__token__'] = $data['__token__'];
            $errorData = (new PicMustValidate())->goCheck();
            if ($errorData !== true) {
                return redirect('/pic/curdPic', [], 500, ['error'=>$errorData,'data' => $data]);
            }
            /**处理数据*/
            $ret = $this->model->curdMess($request);
            if ($ret) {
                $this->success(isset($data['id'])&&$data['id']>0?'修改成功':'添加成功', '/pic/picList', [], 1);
            } else {
                return redirect('/pic/curdPic', [], 500, ['error'=>[isset($data['id'])&&$data['id']
                    ?'修改失败':'添加失败'],'data' => $data]);
            }
        } else {
            $data = $request->param();
            if ($data) {
                $ret = $this->model->editOnePic($data['id']);
            } else {
                $ret['id'] = 0;
                $ret['pic'] = '';
                $ret['alt'] = '';
                $ret['class_id'] = '';
            }
            $ret['class_list'] = [['id'=>1,'class_name'=>'banner'],['id'=>2,'class_name'=>'公司荣誉'],
                ['id'=>3,'class_name'=>'关于我们']];
            return $this->fetch('curdPic', ['top_name'=>'图片管理', 'version'=>'1.0', 'ret'=>$ret]);
        }
    }


    public function picTrash(Request $request)
    {
        $data = $request->param();
        $list = $this->model->picList(12, $data, 9);
        $this->assign('list', $list);
        return $this->fetch('picList', ['top_name'=>'图片回收站', 'version'=>'1.0', 'search'=>
            $data?$data:['search'=>'']]);
    }

    public function restoreDelPic(Request $request)
    {
        $data = $request->param();
        $status = $data['status'];
        $id = $data['id'];
        $ret = $this->model->delPic($id, $status);
        if ($ret) {
            $this->success($status?'删除成功':'还原成功', '/pic/picList', [], 1);
        } else {
            $this->error($status?'删除失败':'还原失败', '/pic/picList', [], 1);
        }
    }
}
